# joint: [roll, pitch, yaw]
# no_joint when not use
mapping: 
  spine:      [no_joint, no_joint, no_joint]
  neck:       [no_joint, no_joint, no_joint]
  # Left arm
  l_shoulder: [no_joint, no_joint, no_joint]
  l_elbow:    [no_joint, no_joint, no_joint]
  l_wrist:    [no_joint, no_joint, no_joint]
  # Right arm
  r_shoulder: [right_s0, right_s1, -right_e0]
  r_elbow:    [right_e1, no_joint, -right_w0]
  r_wrist:    [no_joint, no_joint, no_joint]
