# joint: [roll, pitch, yaw]
# leave it blank '' when not use
mapping: 
  spine: ['hips_r','hips_p','hips_y']
  neck:  ['head_p','head_r','head_y']
  l_shoulder:  ['', '', '']
  l_elbow:  ['', '', '']
  l_wrist:  ['', '', '']
  r_shoulder:  ['r_upper_arm_p', 'r_upper_arm_r', 'r_upper_arm_y']
  r_elbow:  ['r_lower_arm_p', 'r_lower_arm_r', 'r_lower_arm_y']
  r_wrist:  ['', '', '']
